# -*- coding: utf-8 -*-
"""Q2 완료

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14S9jl55Ee7plSk7otpOGtDAyG62o0vW4
"""

# Q2 사용자가 입력한 문자가 소문자면 대문자로, 대문자면 소문자로 바꾸어 출력하는 프로
 
run=False
while not run:
    n=input('알파벳을입력하세요.:')
    for i in n:
        if ord('A') <= ord(i) <= ord('Z'): 
            pass
        elif ord('a') <= ord(i) <= ord('z'): 
            pass     
        elif ' ' in n:
            pass     
        else:
            run=True
    print(f'''입력:{n}
출력:{n.swapcase()}''')
else:
    print('프로그램이 종료됩니다.')

# Q3 입력한 문자열에서 숫자, 영문 소문자, 영문 대문자, 한글, 기타 문자를 골라서 출력하는

n=input('문자열을 입력하세요:')

대문자=''
소문자=''
숫자=''
한글=''
기타=''



run=False
while not run:
    n=input('알파벳을입력하세요.:')
    for i in n:
        if ord('A') <= ord(i) <= ord('Z'): 
            pass
        elif ord('a') <= ord(i) <= ord('z'): 
            pass      
        else:
            run=True


    for i in n:
        if ord('A') <= ord(i) <= ord('Z'): 
            대문자 += i 
        elif ord('a') <= ord(i) <= ord('z'): 
            소문자 += i
        elif ord('0') <= ord(i) <= ord('9'):
            숫자 += i
        elif ord('가') <= ord(i) <= ord('힣'): 
            한글 += i
        else:
            기타 += i

print(f'''대문자:{대문자}
소문자:{소문자}
숫자:{숫자}
한글:{한글}
기타:{기타}''')