# -*- coding: utf-8 -*-
"""Q3 완료

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WWfvHpzZb06aJsEtFCc_tFPkpXrCkrJG
"""

# Q3 입력한 문자열에서 숫자, 영문 소문자, 영문 대문자, 한글, 기타 문자를 골라서 출력하는

n=input('문자열을 입력하세요:')

대문자=''
소문자=''
숫자=''
한글=''
기타=''

for i in n:
    if ord('A') <= ord(i) <= ord('Z'): 
        대문자 += i 
    elif ord('a') <= ord(i) <= ord('z'): 
        소문자 += i
    elif ord('0') <= ord(i) <= ord('9'):
        숫자 += i
    elif ord('가') <= ord(i) <= ord('힣'): 
        한글 += i
    else:
        기타 += i

print(f'''대문자:{대문자}
소문자:{소문자}
숫자:{숫자}
한글:{한글}
기타:{기타}''')