# -*- coding: utf-8 -*-
"""Q4 완료

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZcXQq4OjeW80LBpV6Vu9PrOzsxPZupxt
"""

# Q4 재귀 호출 함수를 이용해서 입력한 10진수를 2진수/8진수/16진수로 변환하는 코드를

 
n=int(input('10진수 입력:'))

print(f'''2진수:{(' ').join(bin(n)[2:])}
8진수:{(' ').join(oct(n)[2:])}
16진수:{(' ').join(hex(n)[2:])}''')