# -*- coding: utf-8 -*-
"""Q5 완료

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1stoTwMvQ0mVJxEldaoHQJ0G2BGM6KFk2
"""

# Q5  주사위 게임을 만드시오 주사위 게임은 주사위를 던져서 높

import random

사람경기내용=[]
컴퓨터경기내용=[]
승패=[]

n1=[1,2,3,4,5,6]

게임횟수=int(input('게임횟수를 입력하시오:'))
print(f'게임을 {게임횟수}회 시작합니다.')

for i in range(게임횟수):
    컴퓨터주사위=random.sample(n1,1)  #n1에서 하나를 뽑는다
    print(f'''
{i+1}회차
컴퓨터:{컴퓨터주사위}     
주사위를 굴리시오''',end='') 
    input()   
    사람주사위=random.sample(n1,1)
    print(f'플레이어:{사람주사위}')
    사람경기내용.append(사람주사위)
    컴퓨터경기내용.append(컴퓨터주사위)
    if 사람주사위 > 컴퓨터주사위 :
        승패.append('승리')
    elif 사람주사위 < 컴퓨터주사위 :
        승패.append('패배')
    elif 사람주사위 == 컴퓨터주사위 :
        승패.append('비김')

print('결과')
print(f'{게임횟수}번 경기내용')

for i in range(게임횟수) :
    print(f'''{i+1}회차 - 플레이어:{사람경기내용[i]}, 컴퓨터:{컴퓨터경기내용[i]} {승패[i]}''')

print(f"게임수:{게임횟수}회 승리:{승패.count('승리')}회 비김:{승패.count('비김')}회 패배:{승패.count('패배')}회")
