# -*- coding: utf-8 -*-
"""Q1 연승미구현

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TK3-qbD0UHI6hBBtai74zf3gDdB6xAYg
"""

# 연승 - 미구현
import random
게임수=[]
while True:
   
    n1=input(f'가위바위보 게임을 시작합니다. 가위,바위,보 중 하나를 입력하세요.:')
    n2=['가위','바위','보']
    n3=random.sample(n2,1)
    print(f'컴퓨터:{n3}')

    if n1=='가위' and '가위' in n3:
        print('비김')
        게임수.append(3)
    elif n1=='가위' and '바위' in n3:
        print('패배')
        게임수.append(2)
        break
    elif n1=='가위' and '보' in n3:
        print('승리')
        게임수.append(1)

    elif n1=='바위' and '가위' in n3:
        print('승리')
        게임수.append(1)
    elif n1=='바위' and '바위' in n3:
        print('비김')
        게임수.append(3)
    elif n1=='바위' and '보' in n3:
        print('패배')
        게임수.append(2)
        break

    elif n1=='보' and '가위' in n3:
        print('패배')
        게임수.append(2)
        break
    elif n1=='보' and '바위' in n3:
        print('승리')
        게임수.append(1)
    elif n1=='보' and '보' in n3:
        print('비김')    
        게임수.append(3)
print()
print(f'''결과
게임수:{len(게임수)}회 승리:{게임수.count(1)}회''')

#
#max_count = 0
#count = 0
#
#for i in range(len(게임수)):
 #   if 게임수[i] == 1:
 #       
  #      for i in range(0, len(게임수)-1):
   #         if 게임수[i] == 게임수[i+1]:
    #            count += 1
     #   else:
      #      if max_count < count:
       #         max_count = count
        #        count = 0
#
#print(f'''결과
#게임수:{len(게임수)}회 승리:{게임수.count(1)}회 연승:{max_count}회''')
