# -*- coding: utf-8 -*-
"""Q1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TK3-qbD0UHI6hBBtai74zf3gDdB6xAYg
"""

 
import random
게임수=[]
while True:
   
    n1=input(f'가위바위보 게임을 시작합니다. 가위,바위,보 중 하나를 입력하세요.:')
    n2=['가위','바위','보']
    n3=random.sample(n2,1)
    print(f'컴퓨터:{n3}')

    if n1=='가위' and '가위' in n3:
        print('비김')
        게임수.append(3)
    elif n1=='가위' and '바위' in n3:
        print('패배')
        게임수.append(2)
        break
    elif n1=='가위' and '보' in n3:
        print('승리')
        게임수.append(1)

    elif n1=='바위' and '가위' in n3:
        print('승리')
        게임수.append(1)
    elif n1=='바위' and '바위' in n3:
        print('비김')
        게임수.append(3)
    elif n1=='바위' and '보' in n3:
        print('패배')
        게임수.append(2)
        break

    elif n1=='보' and '가위' in n3:
        print('패배')
        게임수.append(2)
        break
    elif n1=='보' and '바위' in n3:
        print('승리')
        게임수.append(1)
    elif n1=='보' and '보' in n3:
        print('비김')    
        게임수.append(3)
print()
print(f'''결과
게임수:{len(게임수)}회 승리:{게임수.count(1)}회''')
 
